### ISSUE TITLE
The onValueChanged function is not executed in index 0

### ISSUE THREAD

**Issue by MrKarimi9425** [quidone/react-native-wheel-picker#13]
The onValueChanged function is not executed when scrolling to index 0. Please help

**Comment by serhiihiba** [comment]
Found the same issue today! @rozhkovs when value changing from any element to 0 - event `onValueChanged` isn't triggered

**Comment by rozhkovs** [comment]
hm... I'll try to watch it tomorrow. Can you give me an example?

**Comment by serhiihiba** [comment]
@rozhkovs sure, please, watch the video. It works for an simple example from the docs too

https://github.com/user-attachments/assets/1962341d-856f-462d-baf1-63bff0719d64

**Comment by rozhkovs** [comment]
@MrKarimi9425 @serhiihiba 
Do you use the `value` property for the updated value? The lower example correctly handles the 0 index. 

I agree that this is a problem, and there are 2 ways to solve it:
1. Change the type: make `value` a required property.
2. Handle such a case correctly, but then it is probably necessary to use a new property similar to initialIndex.

Which option do you think is a good one? I'm leaning more towards 1 so far.


```typescript
const SimplePicker = () => {
  const data = useInit(() =>
    [...Array(100).keys()].map((index) => createPickerItem(index)),
  );
  const [value, setValue] = useState(0);

  return (
    <ExampleWheelPicker
      data={data}
      value={value}
      onValueChanged={({item: {value: val}}) => setValue(val)}
      width={100}
    />
  );
};
```

**Comment by MrKarimi9425** [comment]
> @MrKarimi9425 @serhiihiba Do you use the `value` property for the updated value? The lower example correctly handles the 0 index.
> 
> I agree that this is a problem, and there are 2 ways to solve it:
> 
> 1. Change the type: make `value` a required property.
> 2. Handle such a case correctly, but then it is probably necessary to use a new property similar to initialIndex.
> 
> Which option do you think is a good one? I'm leaning more towards 1 so far.
> 
> ```ts
> const SimplePicker = () => {
>   const data = useInit(() =>
>     [...Array(100).keys()].map((index) => createPickerItem(index)),
>   );
>   const [value, setValue] = useState(0);
> 
>   return (
>     <ExampleWheelPicker
>       data={data}
>       value={value}
>       onValueChanged={({item: {value: val}}) => setValue(val)}
>       width={100}
>     />
>   );
> };
> ```

thank you. My problem is solved. Just for not using the `value` property
