### ISSUE TITLE
bug: VirtualizedWheelPicker scrolling breaks when the initial value points to a non-0 index on Android

### ISSUE THREAD

**Issue by rozhkovs** [quidone/react-native-wheel-picker#20]
Expo 51

https://github.com/user-attachments/assets/d59e9312-26bd-4a77-96fc-be0be6d32e74

**Comment by evrrnv** [comment]
The issue is still there

https://github.com/user-attachments/assets/8f199a47-c25a-4f99-bae8-cc84f35188e7

I'm using v1.3.2

**Comment by rozhkovs** [comment]
@evrrnv  Thanks for the video! 
It looks like there are performance issues here and because of this, the animation doesn't have time to work. Have you tried changing the windowsSize by any chance? Please create a Snack with an example of this problem.
