### ISSUE TITLE
Feature: number of visible items

### ISSUE THREAD

**Issue by Alaa-Ben** [quidone/react-native-wheel-picker#9]
Hey there !

Is it possible to configure the number of visible items ? It seems like it's 5 by default (2 above, the selected one, then 2 below). 
Is it possible to customise it to get it down to for example 3 ? (one above, the selected one, and the one below)

Thanks !

**Comment by rozhkovs** [comment]
Hi @Alaa-Ben!

There is no easy way to do this yet, but you can use a more complex way for any animation: redefine the `renderItemContainer` and calculate animation rules for each index based on the `useScrollContentOffset` and your data.

**Comment by Alaa-Ben** [comment]
Thanks for the reply!
I've checked the source code and I see some occurrences of hard coded fives, etc.

Do you think making it customisable is interesting enough to make it a feature in this lib ?

**Comment by rozhkovs** [comment]
> Do you think making it customisable is interesting enough to make it a feature in this lib ?

Yes, it seems to me that this will be a useful feature!

Speaking from the point of view of the public API, it seems that it would be nice to provide the ability to simply specify the visible faces of the drum, for example, 3, 5, 7, etc.

But these are my first thoughts so far, maybe you have better ideas!

**Comment by rozhkovs** [comment]
@Alaa-Ben Released in 1.1.0!)

**Comment by Alaa-Ben** [comment]
Love it, very helpful thanks a lot !
